### PR TITLE
Maui: Updated UI in MapView category samples

### PR DESCRIPTION
**Pull request by duffh**
# Description

Updated UI for samples in the MapView category.

## Type of change

- [x] Bug fix

**Platforms tested on**:

- [x] MAUI Windows
- [x] MAUI Android
- [ ] MAUI iOS

## Checklist

- [ ] Runs and compiles on all active platforms
- [ ] Legacy platforms still compile and run (if applicable)
- [ ] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [ ] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] `sample_sync.py` runs without making changes
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] Code is commented with correct formatting
- [ ] All variable and method names are good and make sense
- [ ] There is no leftover commented code
- [ ] Screenshots are correct size and display in description tab

### CODE REVIEW

**Review by nCastle1 — CHANGES_REQUESTED** [review]
- Action sheet, used in change viewpoint, is broken on both Android and mac catalyst
- Display Drawing Status, consider putting the activity indicator in the control panel. Currently it is very hard to see and disrupts mapview interaction
- DisplayGrid could benefit from rowspacing on the inner grid within the scrollview
- ShowMagnifier - on Android in landscape the label part takes too much space. 
- MapRotation is almost impossible to use in landscape on Android devices with gesture navigation enabled
- DisplayLayerViewState on Android in landscape would work better if there was max width on the label
- DisplayDrawStatus - activity indicator never goes away, appears to be rapidly displayed and hidden before much of the animation progresses on Android

**Comment by ZackAllen** [comment]
Change viewpoint - should be changed to `Application.Current.MainPage.DisplayActionSheet`
Display grid - butons could use spacing, buttons cut off in horizontal on mobile
Map rotation - slider is too small in mobile horizontal.
Show magnifier - label is cutoff on mobile portrait
Take screenshot - close screenshot button not visible on desktop

**Comment by duffh** [comment]
Thanks for the feedback, I've addressed all the comments.

The issue with the rapidly appearing and disappearing activity indicator is a problem I can't see a solution for.

**Review by nCastle1 — APPROVED** [review]
Display Grid is hard to use in landscape; could benefit from a scroll view, but I'm not sure it is worth the effort.

Everything else looks good.

**Pull request merged**
