### PR TITLE
OAuth samples 

### PR DESCRIPTION
**Pull request by ThadT**
These are not accessible from the viewers, but are separate projects found in the "Security" folders (under both Windows and Desktop).

#159

### CODE REVIEW

**Comment by ThadT** [comment]
@anttikajanus @dkemlage @macca400 
Anyone up for reviewing these? I reckon this probably belongs in the quartz-beta branch as well ... I can update the pull request after a review.

**Comment by anttikajanus** [comment]
I can have a look tomorrow. I need to make some comments to the common security samples anyway.

**Comment by anttikajanus** [comment]
@ThadT should this be against quartz beta or v.next branch?

**Comment by ThadT** [comment]
@anttikajanus quartz-beta ... sorry for the confusion. I can update the PR

**Pull request closed without merging**
