### PR TITLE
Implement find address samples

### PR DESCRIPTION
**Pull request by nCastle1**

### CODE REVIEW

**Comment by nCastle1** [comment]
@dkemlage Can you please take a look at this? It implements the 'Find Address' sample and includes improvements from your earlier review of #266.

**Comment by nCastle1** [comment]
@dkemlage I've reviewed and merged in master, this should be ready for your final review. Note: I double checked the TypeLinks and all three do not currently have samples.

**Comment by dkemlage** [comment]
@nCastle1 This is what I have for the code review process.

~ After doing testing on several platforms, I am now convinced that a little redesign will be required to make the sample public. We either need to (1) add a Button that the user clicks that invokes the UpdateSearch function call rather than the TextBox.textChanged Event or (2) get rid of the option to enter user provided addresses (i.e. only use the pre-canned addresses in the ComboBox). As I was entering a custom address in the TextBox the map would lock up and switch locations several times - this is not a good user experience.  

~ There is mismatch with the LineFeed settings on your Visual Studio configuration (as compared to the other members of the team) that prompts the following dialog when I open any of the .sln files:
image
You are welcome to look at my Visual Studio settings to see if there are differences.

~ I found a few additional TypeLinks that you can use in the metadata.json file that will increase exposure for your sample to be showcased in the LibRefAPI documentation pages. Please add these TypesLinks:
"T:Esri.ArcGISRuntime.Tasks.Geocoding.LocatorTask" 
"T:Esri.ArcGISRuntime.Tasks.Geocoding.GeocodeResult" 
"T:Esri.ArcGISRuntime.Tasks.Geocoding.SuggestResult"
"M:Esri.ArcGISRuntime.Tasks.Geocoding.LocatorTask.CreateAsync(System.Uri,Esri.ArcGISRuntime.Security.Credential)"
"M:Esri.ArcGISRuntime.Tasks.Geocoding.LocatorTask.SuggestAsync(System.String)"
"M:Esri.ArcGISRuntime.Tasks.Geocoding.LocatorTask.ReverseGeocodeAsync(Esri.ArcGISRuntime.Geometry.MapPoint)"
"P:Esri.ArcGISRuntime.Tasks.Geocoding.GeocodeResult.Attributes"
"M:Esri.ArcGISRuntime.UI.Controls.GeoView.IdentifyGraphicsOverlaysAsync(System.Windows.Point,System.Double,System.Boolean)"
"M:Esri.ArcGISRuntime.UI.Controls.MapView.ScreenToLocation(System.Windows.Point)"
"M:Esri.ArcGISRuntime.UI.Controls.GeoView.IdentifyGraphicsOverlaysAsync(Windows.Foundation.Point,System.Double,System.Boolean)"
"M:Esri.ArcGISRuntime.UI.Controls.MapView.ScreenToLocation(Windows.Foundation.Point)"
"M:Esri.ArcGISRuntime.UI.Controls.GeoView.IdentifyGraphicsOverlaysAsync(CoreGraphics.CGPoint,System.Double,System.Boolean)"
"M:Esri.ArcGISRuntime.UI.Controls.MapView.ScreenToLocation(CoreGraphics.CGPoint)"
"M:Esri.ArcGISRuntime.UI.Controls.GeoView.IdentifyGraphicsOverlaysAsync(Android.Graphics.PointF,System.Double,System.Boolean)"
"M:Esri.ArcGISRuntime.UI.Controls.MapView.ScreenToLocation(Android.Graphics.PointF)"

Hold off on marking your issue as 'DONE' until after we check the LibRefAPI doc to see if your sample is showcased as we hope given the different platform usages of Point, PointF, GCPoint, etc. 

That's it for now. I look forwards to reviewing your next round of changes. - don

**Comment by nCastle1** [comment]
@dkemlage This should now be ready for re-review

**Comment by dkemlage** [comment]
@nCastle1 The sample functions much better with a button click to find user entered locations. Thanks for making the modifications. Please merge into master.
NOTE: If you have to update the .csproj and .vbproj files to account for merge conflicts please ensure you run the applications prior to the merge to ensure nothing is broken.

**Pull request merged**
