### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by anttikajanus**
Fixed
- Force hittesting to local cache on feature layer sample
- Fixed some simple UI issues and confusing method names
- Added UnhandledException handler to desktop
- Fixed Elevation Exaggeration sample

### CODE REVIEW

**Comment by anttikajanus** [comment]
@mbranscomb could you have a look for this?

**Comment by anttikajanus** [comment]
@mbranscomb added CurrentDomain.UnhandledException handler.

**Comment by mbranscomb** [comment]
@anttikajanus Looks good to me - made a minor comment regarding use of the PropertyChanged event in SmoothGraphicAnimation sample (but then I wrote that sample originally!)

**Comment by anttikajanus** [comment]
@mbranscomb  updated.

**Pull request merged**
