### PR TITLE
Updated Configurations

### PR DESCRIPTION
**Pull request by mbranscomb**

### CODE REVIEW

**Comment by mbranscomb** [comment]
@ZackAllen Only created this as a draft PR for now - maybe you could pull the branch and give it a try?

It removes a significant number of invalid build combinations.

**Review by ZackAllen — COMMENTED** [review]
The Xamarin.Forms solution still features ARM instead of ARM64. The solutions that are changed work as expected.

**Comment by ZackAllen** [comment]
I made fixes to the Forms solution and the Xamarin solution, this is ready for re-review.

**Comment by mbranscomb** [comment]
@ZackAllen Thanks. Tested, pushed some more updates, and re-requested review.

**Review by ZackAllen — APPROVED** [review]
Tried the new Forms solution and everything works correctly.

**Pull request merged**
