### PR TITLE
Forms sample fixes from certification

### PR DESCRIPTION
**Pull request by nCastle1**
This PR addresses several issues:
* *Forms all* **Author and save a map**, **Search a portal for maps** - crash when empty OAuth settings entered [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/bb10a1df3eace2a27b00f6152f1566cc8a9d737e)
* *Forms UWP* **Open map (URL)** - crash when pressing Maps button multiple times [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/dc879d828c224331a2f3bb7c4ca3ade1fae6ad38)
* *Forms UWP* **Display drawing status** - status bar is missing [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/2544b6014304814da31066ace0e051216c181439)
* *Forms iOS* **Query feature count and extent** - button text is truncated [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/add74b8fc1c2feee863d8e8d9261fe577eb3581e)
* *Forms iOS* **Map rotation**, **Densify and generalize**, **Line of sight (GeoElement)** - sliders hard to use on iOS due to conflict with OS navigation gesture [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/005b07d4ecd64cd9360f96e7e92eec57d692ba3f)
* *Forms all* **Map rotation** - slider/label UI could be improved [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/005b07d4ecd64cd9360f96e7e92eec57d692ba3f)
* *Forms UWP* **Take screenshot** - preview button missing [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/commit/60810ce306c89c82713c9ead68f47db378155db7)
* *Forms UWP* **Find service area (interactive)** - missing newlines in instructions [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/adbd9ade0b4ff85c39e51b3075b35109a584402e)
* *Forms all* **All samples** - some samples set title manually leading to mismatches; samples should be updated to not set title; the viewer can do it automatically. [commit](https://github.com/Esri/arcgis-runtime-samples-dotnet/d111f7d8edcca31b891ca3b19f48aa0dff1a04b0)

### CODE REVIEW

**Comment by pragatisahu** [comment]
Below are my findings:
1. Search a port (iOS only): `Search Maps` and `My maps` button can have more space between them. (Enhancement)
2. Map rotation (Android only): slider bar not visible in android devices.
[Samsung Galaxy phone](https://user-images.githubusercontent.com/40747019/49184904-5aeacc00-f315-11e8-84bd-2226fd14da99.png)
3. Find service area (interactive) sample (All Forms): `)` missing in the title bar
4. Description screenshot to be changed for the following sample:
    - Take screenshot
    - Display drawing status
    - Author and save a map
    - Search a portal for maps
    - Map rotation

**Comment by dkemlage** [comment]
I found similar issues as Pragati. Additionally I found:

(a) The Xamarin.Forms.Android version of the 'Author and Save a Map' sample does not show all of the pre-populated login information:
image

(b) I found that samples that use a slider in Xamarin.Forms.Android ('Map rotation' and 'Densify and Generalize') that the knob for the slider appears but not the line that it slides along. Could this be changed by a background color property setting?

(c) @nCastle1 if you want, I can re-capture all the screen shots for the samples that changed and create a separate PR for that. **Let me know what you decide.** As an FYI, these are the guidelines for capturing the screen shots:
~ SnagIt (ver 2019.0.0 Build 2339) with the fixed region option and then in the SnagIt Editor added a 3 pixel solid black border around the image.
~ WPF - SnagIt fixed region 796x594 + 3 black pixel margin = 800x600 final image dimensions
~ UWP- SnagIt fixed region 796x594 + 3 black pixel margin = 800x600 final image dimensions
~ Xamarin.iOS - SnagIt fixed region 656x830 + + 3 black pixel margin = 662x836 final image dimensions via the iPad Pro 10.5 inch iOS 11.2 Emulator
~ Xamarin.Android - SnagIt fixed region 457x652 + + 3 black pixel margin = 463x658 final image dimensions via the Pixel Android 8.1 - API 27 Emulator

**Comment by dkemlage** [comment]
After talking with @nCastle1 we decided to create additional Pull Requests for those issues that were found during the QA of this PR.

**Comment by dkemlage** [comment]
Merging this PR on behalf of @nCastle1 while he is out on vacation.

**Pull request merged**
