### PR TITLE
Find route sample

### PR DESCRIPTION
**Pull request by ThadT**
Simple routing sample: two stops, no barriers. Click to solve route and get directions.

### CODE REVIEW

**Comment by ThadT** [comment]
Hey @nCastle1 ... would you mind taking a look at this if you have time?

**Comment by nCastle1** [comment]
@ThadT I noticed that the screenshots were out of date for some of the samples. As I had to open and run the samples to review them, I decided to save some time and take screenshots simultaneously. With those changes having been made, this looks good and ready to merge.

**Comment by nCastle1** [comment]
@ThadT Fully tested on all platforms post-merge, ready to merge into master.

**Comment by ThadT** [comment]
Thanks @nCastle1 !

**Pull request merged**
