### PR TITLE
Recent samples warnings addressed and code styled

### PR DESCRIPTION
**Pull request by williambohrmann3**
# Description

- Addresses code-related warnings introduced with `AddDynamicEntityLayer` and `CreateLoadReport` samples.
- XAML styler and CodeMaid ran

## Type of change

- Other enhancement

## Platforms tested on

- [x] WPF .NET 6
- [x] WPF Framework
- [x] WinUI
- [x] MAUI WinUI
- [x] MAUI Android
- [x] MAUI iOS
- [x] MAUI MacCatalyst

## Checklist

- [x] Self-review of changes
- [x] All changes work as expected on all affected platforms
- [x] There are no warnings related to changes
- [x] Code is commented and follows .NET conventions and standards
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] No unrelated changes have been made to any other code or project files

### CODE REVIEW

**Comment by williambohrmann3** [comment]
All devices behaving as expected; only exception being iOS with `AddDynamicEntityLayer`, an exception is being thrown on line 56 on my branch. This is a regression from the previous branch. Trying to understand why `Initialize()` needs to be `async` specifically for iOS and not elsewhere, especially considering the lack of `await` calls in the method.

**Comment by williambohrmann3** [comment]
Call stack when opening said sample from MAUI.iOS viewer (breakpoint on line 56): Screen Shot 2023-05-08 at 4 47 50 PM

**Comment by williambohrmann3** [comment]
Confirmed that `AddDynamicEntityLayer` works on a physical iPad when running my branch.

**Comment by williambohrmann3** [comment]
Also, `CreateLoadReport` is impacted by this MAUI.WinUI [issue](https://github.com/dotnet/maui/issues/14557) which is why our `CollectionView` headers aren't showing just on Windows.

**Review by amweis226 — APPROVED** [review]

**Pull request merged**
