### PR TITLE
Update packages to 100.5 to enable LS testing

### PR DESCRIPTION
**Pull request by nCastle1**

### CODE REVIEW

**Comment by pragatisahu** [comment]
Tested with build: 22310 and LS 100.5. All the the LS samples of WPF is working perfectly fine.

**Comment by dotMorten** [comment]
Closing for now. Keep the branch but wait for PR till we ship 100.5.

**Comment by dkemlage** [comment]
@dotMorten Can we re-open this issue and get this PR merged into v.next? I need to start building the LibRefAPI documentation for 100.5.

**Comment by dotMorten** [comment]
Sorry missed this was for the vnext branch

**Pull request merged**
