### PR TITLE
Show Callout Sample

### PR DESCRIPTION
**Pull request by nCastle1**
Sample demonstrates how to show a callout on the map in response to a user’s interaction.

### CODE REVIEW

**Comment by nCastle1** [comment]
@dkemlage This is ready for review. I've made the changes you mentioned from your initial review

**Comment by nCastle1** [comment]
@dkemlage This is now ready for review and merge if acceptable (conflicts have been resolved).

**Comment by dkemlage** [comment]
@nCastle1 I made some initial code changes to the WPF project (C# and VB.NET). Please make likewise changes to the other platforms. Be extra careful with modifications to the .csproj and .vbproj files to make sure they work given the merge conflicts addressed.

**Comment by dkemlage** [comment]
@nCastle1 Your code is awesome! Please merge.

**Pull request merged**
